application: weavrs-dev-hrd
version: hello
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /hello-static
  static_files: helloworld.html
  upload: helloworld.html
  expiration: 1m

# - url: /hello-cgi
#   script: helloworld.py

- url: /hello-wsgi
  script: hellowsgi.application
  #script: hellowsgi.py

- url: /hello-cache
  script: hellocache.application
  #script: hellocache.py

- url: /hello-memcache
  script: hellomemcachemany.application
  #script: hellomemcachemany.py

- url: /hello-datastore
  script: hellodatastoremany.application
  #script: hellodatastoremany.py

# - url: /hello-django
#   script: djangoappengine.main

- url: /
  static_files: index.html
  upload: index.html
  expiration: 1m

- url: /_ah/warmup.*
  script: warmup.application
